import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import CTA from "./components/CTA";
import Footer from "./components/Footer";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
  weight: ["400", "700"],
});
// Lexend Deca is used for the body text
// Space Mono is used for the code blocks

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} ${lexendDeca.variable} antialiased`}
      >
      <Nav />
        {children}
        <CTA />
        <Footer />
      </body>
    </html>
  );
}
